#+title: Emacs Config
#+STARTUP: overview
#+HTML_HEAD: <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

Denne Emacs-konfigurasjonen baserer seg på [[https://github.com/doomemacs/doomemacs][Doom Emacs]]-rammeverket, som deler inn all konfigurasjon til ~init.el~, ~packages.el~, og ~config.el~.

Dette er en [[https://orgmode.org/manual/Extracting-Source-Code.html][literal konfigurasjonsfil]], som betyr at all konfigurasjon defineres i denne artikkelen, også hentes innholdet i kodeblokkene her ut til de riktige konfigfilene når man ønsker å oppdatere. Med andre ord skriver man README-en først, også utgår all konfig automatisk ut fra den. 

* Profiling av oppstartstid


Om oppstart av Emacs går treigt, pleier jeg å legge inn disse to linjene manuelt henholdsvis topp og bunn av ~config.el~. Da får man en callstack-rapport med ~M-x profiler-report~ der det står ganske tydelig hva som tar opp all tiden:

#+begin_src elisp
(profiler-start 'cpu)
(profiler-stop)
#+end_src


test:

* Toppnivå headere
** packages.el
#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el

;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+end_src

~;; -*- no-byte-compile: t; -*-~ sier at Emacs ikke skal kompilere filen til en ~.elc~-fil. Det blir vanligvis gjort for at ting skal kjøre fortere

** config.el
#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

** init.el

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/init.el
;;; init.el -*- lexical-binding: t; -*-
#+end_src

* Secrets

Sensitiv info som passord, personlige notatnavn, og jobbrelaterte referanser som ikke passer seg på et offentlig repo legges til en ~.emacs.secrets~-fil som jeg synkroniserer privat, utenfor denne configen.

~when~-uttrykket på første linje passer på at Emacs ikke krasjer hvis ~.secrets~-fila skulle mangle

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(when (file-exists-p "~/.emacs.secrets")
  (load-file "~/.emacs.secrets"))
#+end_src



* init.el

Dette er hele ~init.el~-fila slik den er originalt etter Doom Emacs-rammeverket. Har ikke kommet over noen god grunn til å dele den opp

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/init.el
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       ;;company           ; the ultimate code completion backend
       (corfu +orderless)  ; complete with cap(f), cape and a flying feather!
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       smooth-scroll     ; So smooth you won't believe it's not butter
       ;;tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       (dired +dirvish +icons)             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ;;eww               ; the internet is gross
       ;;ibuffer           ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       lookup              ; navigate your code and its documentation
       ;;lsp               ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf               ; pdf enhancements
       terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;tree-sitter       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if (featurep :system 'macos) macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;(cc +lsp)         ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       ;;json              ; At least it ain't XML
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org +roam2 +habit)               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;graphviz          ; diagrams for confusing yourself even more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubeS
       ;;yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader

       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src
* packages.el

Her ligger det småpakker som ikke har gjort seg fortjent til egne kapitler

- ~rainbow-mode~ fargelegger hexnumre direkte, f.eks. #EEEE3E.
  - Lar den stå avslått til vanlig
- ~keyfreq~ gir statistikk på hvor ofte kommandoer brukes
- ~verb~ er [[https://github.com/federicotdn/verb][herfra]]. Et alternativ til ~restclient.el~
- ~keycast~ er veldig nyttig for å se hvilke funksjoner som kalles

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! fireplace)
(package! rainbow-mode)
(package! vimgolf)
(package! evil-tutor)
(package! elisp-format)
(package! keyfreq)
(package! verb)
(package! keycast)
(package! yankpad)
#+end_src


vimgolf config:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! vimgolf
  (map! :leader
        ;; call vimgolf prompt
        "g v" #'vimgolf
        ;; default bindings as listed in README
        "g V" #'vimgolf-submit))
#+end_src

keyfreq config: Fjerner tracking av scroll-events, for de støyer ned all statistikken.
Fjerner også ~org-self-insert-command~, som kjøres for hvert eneste tastetrykk

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el

(setq keyfreq-excluded-commands
        '(mwheel-scroll
          ultra-scroll
          self-insert-command
          org-self-insert-command))

(setq keyfreq-autosave-timeout 180)
(keyfreq-mode 1)
(keyfreq-autosave-mode 1)
#+end_src
* Consult (søking)

[[https://github.com/minad/consult][Consult]] er ei pakke med søke- og navigeringskommandoer som følger med Doom Emacs.

Consult har mulighet for live preview av filer når man søker opp et ord, men for meg er det ikke aktivert som standard. Legger til live preview slik:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! consult
  (consult-customize
   +default/search-project
   +default/search-other-project
   +default/search-cwd
   +default/search-other-cwd
   consult-ripgrep
   consult-grep
   consult-git-grep
   :preview-key 'any))
#+end_src

Den viktige linja her er ~:preview-key 'any~. Den sier at for alle søkefunksjonene som listes opp i forkant, så skal ethvert tastetrykk ("~any~") trigge preview av valgt fil.

Default-innstilling kan man se ved å slå opp verdien på ~consult--customize-alist~. Hos meg var alle søkekommandoer satt med ~:preview-key 'SPC-C'~, som betyr at jeg måtte eksplisitt taste SPC-C for å trigge en preview før jeg la til denne konfigurasjonen

2026-03-13 Advice for å muliggjøre preview av filer når man søker gjennom filer med ~consult-fg~. Dette er vibe-kode som jeg ikke har tatt meg tid til å forstå. Endte med dette fordi det

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defadvice! my/consult--find-with-preview (orig-fn prompt builder initial)
  :around #'consult--find
  (consult--read
   (consult--process-collection builder
     :transform (consult--async-map (lambda (x) (string-remove-prefix "./" x)))
     :highlight t :file-handler t)
   :prompt prompt
   :sort nil
   :require-match t
   :initial initial
   :add-history (thing-at-point 'filename)
   :category 'file
   :history '(:input consult--find-history)
   :state (consult--file-state)))
#+end_src


** Søkesti-variabel

Noen funksjoner brukes både på jobb og fritid, og avhenger av en path til et par repoer. Typisk søke- og versjonskontrollfunksjoner, som vil si ~Consult~ og ~Magit~ her.

For å unngå to versjoner av alle de funksjonene, har jeg heller en toggle som bytter en sentral pathvariabel, også referer alle funksjonene til den variabelen.

Til slutt er det en indikator i modeline-en som sier om jeg er i fritid- eller jobbmodus akkurat nå 

Sentral pathvariabel:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defvar my/søkesti "~/repos/"
  "Rotsti for consult-søk. Veksle med my/toggle-jobb-fritid.")
#+end_src

Oppretter en indikator til modeline-en, og legger den til modelineconfig:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defvar my/søkesti-indikator "[F]"
  "Modeline-indikator for gjeldende søkesti.")

(add-to-list 'global-mode-string '(:eval my/søkesti-indikator) t)
#+end_src

- ~global-mode-string~ er ei liste over ekstra ting som legges til modeline-en. Her legger vi til indikatoren som sier hvorvidt vi er i jobb- eller fritidsmodus. 
- ~:eval~ og den fnutten i forkant gjør at ~my/søkesti-indikator~ evalueres hver gang modeline blir bedt om å oppdateres, som den blir bedt om hver gang ~my/toggle-jobb-fritid~ kjøres

Togglefunksjonen:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/toggle-jobb-fritid ()
  "Veksler my/søkesti mellom jobb og fritid."
  (interactive)
  (setq my/søkesti
        (if (string= my/søkesti "~/repos/jobb/")
            "~/repos/"
          "~/repos/jobb/"))
  (setq magit-repository-directories
        `((,my/søkesti . 5)))
  (setq my/søkesti-indikator
        (if (string= my/søkesti "~/repos/jobb/")
            "[J]"
          "[F]"))
  (force-mode-line-update t)
  (message "Søkesti: %s" my/søkesti))
#+end_src

#+RESULTS:
: my/toggle-jobb-fritid

- ~force-mode-line-update t~ sier at modeline-innholdet skal oppdateres
- referanser til "git-depth" er det tallet nedenfor ~magit-repository-directories~, som sier hvor mange subdirectories nedover man skal lete etter git-repoer

Legger til en hotkey for togglefunksjonen: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      :desc "kjører my/toggle-jobb-fritid"
      "t t" #'my/toggle-jobb-fritid)
#+end_src



** Søke gjennom alle repoer etter tekst

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      :desc "Søke etter tekst i alle repoer"
      "S P" (lambda () (interactive)
              (consult-ripgrep my/søkesti)))
#+end_src

~SPC S P~ gjør et tekstsøk gjennom alle filer under ~my/søkesti~. Bruker ~M-x my/toggle-jobb-fritid~ for å veksle mellom jobb og fritid.

** Søke gjennom alle repoer etter filnavn

Samme som over, men for filnavn i stedet for tekstsøk:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      :desc "Søke etter filnavn i alle repoer"
      "S F" (lambda () (interactive)
              (consult-fd my/søkesti)))
#+end_src

~consult-fd~ bruker [[https://github.com/sharkdp/fd][~fd~]] i stedet for ~find~. ~fd~ har bedre config-flagg for å kunne søke opp dotfiler, men samtidig ekskludere ~.git/~, som ville gitt innmari mye støy i søketreffene

* Tema

Dette er temaer jeg har lagt til i tillegg til alle som fins i Emacs fra før.
Siste headline har en ~(setq doom-theme NAVN)~-uttrykk som faktisk velger en av disse

** Kanagawa

Temaet kommer [[https://github.com/emacsmirror/kanagawa-themes][herfra]]. Fargepaletten er inspirert av det japanske [[https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa][Kanagawa-maleriet]]. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! kanagawa-themes)
#+end_src

** Catppuccin

Herfra: [[https://github.com/catppuccin/emacs/][Catppuccin - Soothing pastel theme for Emacs]]

Installerer ~catppuccin~-temaet gjennom ~packages.el~

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! catppuccin-theme)
#+end_src

Deretter må det settes i ~config.el~ vha. ~doom-theme~. Temaet kommer i fire varianter (Latte, Frappé, Macchiato, Mocha), også setter en av disse via en "flavor"-string. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq catppuccin-flavor 'mocha)
(setq catppuccin-flavor 'macchiato)
#+end_src

...da jeg la inn dette fikk jeg en feilmelding om *Symbol’s function definition is void*, som jeg løste med en blanding av løsningen fra et [[https://github.com/catppuccin/emacs/issues/121][GitHub-issue]] og litt vibe-code fra ChatGPT:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(add-hook 'server-after-make-frame-hook
          (lambda () (when (fboundp 'catppuccin-reload)
                       (catppuccin-reload))))

(when (fboundp 'catppuccin-reload)
  (catppuccin-reload))
#+end_src

#+RESULTS:
: t

** Modus Vivendi
Protesilaos' temaer: https://protesilaos.com/emacs/modus-themes

De er blitt tatt inn som standardtemaer i Emacs, så det er bare å sette dark-versjonen (~modus-vivendi-tinted~) som standard

** Standardtema

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq doom-theme 'modus-vivendi-tinted)
#+end_src


* Generell Emacs config
** Størrelse på vinduet ved oppstart

Dette er for å få Emacs til å starte opp med en hensiktsmessig størrelse på vinduet, slik at jeg slipper å resize-e det hver gang Emacs starter opp. 

For å se størrelsen på vinduet akkurat nå, kan man evaluere denne:

#+begin_src emacs-lisp
(format "Width: %d, Height: %d" (frame-width) (frame-height))
#+end_src

#+RESULTS:
: Width: 95, Height: 50

WSL og Linux oppfører seg forskjellig, så de trenger hver sin setting:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(cond
 ;; ---  WSL  ---
 ((and (eq system-type 'gnu/linux) (getenv "WSLENV"))
  (add-to-list 'initial-frame-alist '(width . 95))
  (add-to-list 'initial-frame-alist '(height . 50)))

 ;; --- Linux ---
 ((eq system-type 'gnu/linux)
  (add-to-list 'initial-frame-alist '(width . 83))
  (add-to-list 'initial-frame-alist '(height . 43))))
#+end_src

Ved første øyekast ser det ut som om vinduet settes til å være nesten dobbelt så bredt som det er høyt, før man skjønner at høyden oppgis i linjer, og bredden oppgis i antall characters.

Det gir mening når man får høre at Emacs måler alt i tekst, og rektangelet som omslutter en bokstav på datamaskiner er mye høyere enn det er bredt.


** Kill ring max
Emacs' lagrer utklippstavlen over tid, men standard maxlengde for historikken er 120 entries, som ikke er så mye. Øker denne en del:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq kill-ring-max 1000)
#+end_src

** Fjern word wrap

Det er egentlig fint at ord wrapper på høyresiden av skjermen, men ~word-wrap~ gjør også at URL-er starter med et linjeskift, og det er irriterende. Håper å finne ut en måte å fjerne bare newline på venstresiden, samtidig som jeg kan beholde vanlig word wrap på høyresiden

Det er uansett raskt å bytte mellom modusene med ~M-x toggle-ord-wrap~. Setter default til å ikke bryte:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
;(setq word-wrap nil)
(add-hook 'doom-after-init-modules-hook
  (lambda () (setq-default word-wrap nil)))
#+end_src

** Nerd fonts

[[https://www.nerdfonts.com/][Nerd Fonts]] brukes aktivt i Doom Emacs til alle mulige små symboler rundt omkring. 

På Linux kan man installere Nerd Fonts med ~M-x install-nerd-fonts~, men Emacs som kjører under WSL/Windows eller på Termux/Android klarer ikke det. Da må man i tillegg installere en font selv, også deretter sette den med ~doom-font~.

Det som er ekstra spennende, er at hele Doom Emacs-korthuset ramler sammen dramatisk hvis man prøver å sette ~doom font~ til noe som ikke fins. Så for å sikre mot det, ligger ~setq doom-font~ etter en ~when~-clause som sjekker om den fins før vi setter den

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(when (find-font (font-spec :family "FantasqueSansM Nerd Font"))
  (setq doom-font (font-spec :family "FantasqueSansM Nerd Font" )))
#+end_src

(setq doom-font (font-spec :size 15 ))

Installasjon av nerd fonts kan gjøres sånn:
*** Hvordan installere Nerd Fonts:

1. Last ned en font-variasjon av Nerd Fonts, f.eks. ~Fantasque~, [[https://www.nerdfonts.com/font-downloads][herfra]]
   - [[https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FantasqueSansMono.zip][Direktelenke til FantasqueSansMono.zip]] 
2. Ekstraher ~.zip~-en og gå inn i mappa fra kommandolinjen
3. Kjør dette for å installere fonten: 

#+begin_src shell
mkdir -p ~/.local/share/fonts
cp FantasqueSansMNerdFont-*.ttf ~/.local/share/fonts/
fc-cache -fv
#+end_src 

** Grunnleggende personinfo

Navn og e-post kan finne på å bli printa i eksporterte dokumenter.
Linux, WSL og Android finner på forskjellige ting her, og fyller inn hostname o.l. som standard.
Så jeg setter de eksplisitt her:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq user-full-name "Martin Lillebo"
      user-mail-address "lillebomartin@gmail.com")
#+end_src


** Vindustekst

Dette er linja helt på toppen av hele Emacs-GUI-et

Default fra Doom-config er filnavn + "". Endrer den til å være blank

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq frame-title-format nil)
#+end_src

Lager også en enkel toggle så jeg kan endre til å skrive full path etter behov:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/toggle-vindustekst ()
  (interactive)
  (setq frame-title-format
        (if frame-title-format nil '("%f"))))
#+end_src

        
** Fjerne "are you sure you want to close Emacs? (y/n)"
Sånn:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq confirm-kill-emacs nil)
#+end_src

** Lexical binding

Setter lexical binding som standard, i stedet for dynamic som er (foreløpig fortsatt) default standard:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq-default lexical-binding t)
#+end_src

Forskjellen mellom lexical/dynamic binding handler om hvorvidt verdier satt med ~let~ er tilgjengelige for nøsta funksjoner eller ikke. Lexical er det som er vanlig ellers, f.eks. i Python. Det er bra forklart her: https://web.archive.org/web/20250409165354/https://www.gnu.org/software/emacs/manual/html_node/eintr/Lexical-vs-Dynamic-Binding-Example.html

** Autolagre buffere

Standardinnstillingen til Emacs er at man åpner opp fil-innholdet i en uavhengig buffer, også skrives ikke endringer til filen før man husker å lagre med ~SPC b s~. Det glemmer jeg hele tida, så denne innstillingen aktiverer autolagring-modus med ~+1~ med 5-sekunders intervall mellom hver lagring


#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq auto-save-visited-interval 5)
(auto-save-visited-mode +1)
#+end_src

** Hurtigtaster
*** ~C-s~ for å lagre
~SPC b s~ føles unødvendig når man har ~C-s~ i alle andre programmer i hele verden, så jeg legger inn sistnvente som hotkey til å lagre buffer:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :i "C-s" #'save-buffer   ; insert mode
      :n "C-s" #'save-buffer)  ; normal mode
#+end_src

*** ~SPC y p~: yankpad-insert

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "y p" #'yankpad-insert)
#+end_src

*** ~SPC y k~: yank-from-kill-ring
Bruker denne veldig ofte

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "y k" #'yank-from-kill-ring)
#+end_src
*** ~SPC v s~ for å markere som kode 

jeg ~markerer~ ofte et helt ord og wrapper det i ~tilde~. Da må man skrive "viWS~", som er både blanding av case og et tildesymbol. På et norsk tastatur krever det 9 tastetrykk. Får denne ned til 3 trykk slik:

bruker ~SPC v s~ fordi den minner meg om den originale versjonen.

~evil-forward-WORD-end~ er den funksjonen som er bundet opp til ~e~ i vanlig ~evil-mode~

Lager i tillegg en versjon som bare kjører "S ~" når jeg har markert tekst, slik at jeg har en løsning som også kan håndtere flere ord med mellomrom mellom seg. Da har jeg samme hotkey for normal mode og visual mode. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(define-key evil-normal-state-map (kbd "SPC v s")
  (lambda () (interactive)
    (execute-kbd-macro (kbd "v i W S ~"))
    (evil-forward-WORD-end)))

(define-key evil-visual-state-map (kbd "SPC v s")
  (lambda () (interactive)
    (let ((end-pos (region-end)))
      (execute-kbd-macro (kbd "S ~"))
      (goto-char (+ end-pos 1)))))
#+end_src

** Relative linjenumre
Relative linjenumre gjør det mulig å hoppe til riktig linje med vim motions

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq display-line-numbers-type 'visual)
#+end_src

Det fins også et valg som heter ~'relative~, men da får man bufferlinjer i stedet for skjermlinjer. Da slutter Vim-referanser å virke så fort man har en innsnevring i bufferen.


** Fargelegge linjenumre
Standardfargen for linjenumrene er litt for mørke, som er upraktisk når man ofte refererer til de med vimbindings

Standarden er: 

- Foreground: ~#45475a~
- Background: ~#1e1e2e~

Gjør de lysere slik: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(custom-set-faces!
  '(line-number              :foreground "#b8c2dc"))
#+end_src


** Bokmerker

Gjør at bokmerker holder seg lagra på tvers av reboots:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq bookmark-save-flag 1)
#+end_src
** Deaktivere ~pg dn~ og ~pg up~
Disse er rett ved piltastene på min laptop, og jeg kommer borti de hele tiden. Jeg bruker de ikke til vanlig, så jeg bare deaktiverer de:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(with-eval-after-load 'pixel-scroll
  (defalias 'pixel-scroll-interpolate-down 'ignore)
  (defalias 'pixel-scroll-interpolate-up 'ignore))
#+end_src

uten ~with-eval-after-load~ så funker ikke ~defalias~-uttrykkene, selv om de legges helt nederst i ~config.el~
** Garbage collection-meldinger :noexport:

Setter på denne for å må melding i echo-area når garbage collection starter og slutter. Bare fordi det er interessant å få et inntrykk av hvor ofte det skjer: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq garbage-collection-messages t)
#+end_src

** Gå ut av insert mode etter idletid

Hvis jeg er i idle mode lengre en 30 sek uten aktivitet, så går den ut av insert og inn i normal mode.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(run-with-idle-timer 30 t
  (lambda ()
      (when (evil-insert-state-p)
            (evil-normal-state))))
#+end_src

** Gjennomsiktig bakgrunn og dimming

Alle kule utviklere har delvis gjennomsiktig bakgrunn

~add-to-list~ er der for å gi samme transparens til sekundære Emacs-vinduer, eller "frames" i Emacs-sjargong. Det skjer ikke så ofte, men f.eks. Emacs Everywhere-buffervinduer er selvstående vinduer som ikke blir transparente uten denne innstillingen

Det var nå jeg måtte lære meg hva en "frame" er, i tillegg til "window" og "buffer" 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(set-frame-parameter (selected-frame) 'alpha '(95 . 95))
(add-to-list 'default-frame-alist '(alpha . (95 . 95)))
#+end_src

#+RESULTS:
: ((alpha 96 . 96) (buffer-predicate . doom-buffer-frame-predicate) (right-divider-width . 1) (bottom-divider-width . 1) (alpha 94 . 94) (vertical-scroll-bars) (tool-bar-lines . 0) (menu-bar-lines . 0) (left-fringe . 8) (right-fringe . 8))

** Avslutte med riktig kommando

Jeg lukker ofte Emacs med ~SPC w q~ uten å mene det, da jeg bruker den mye for å lukke vinduer. Om det bare er ett vikdu igjen, så avsluttes Emacs. Fjerner den siste regelen slik:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/evil-quit-advice (orig-fun &rest args)
  "Stopper evil-exit fra å lukke Emacs"
    (if (= (length (window-list)) 1)
          (message "Lukk Emacs med SPC q q")
              (apply orig-fun args)))

(advice-add 'evil-quit :around #'my/evil-quit-advice)
#+end_src

** ultra-scroll

Denne tror jeg er standard i Doom Emacs. Men den gir feilmelding ved oppstart i Android, så jeg deaktiverer den på mobil:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(when (eq system-type 'android)
    (advice-add 'ultra-scroll-mode :override #'ignore))
#+end_src
* Doom modeline

Mesteparten av modeline-en går med til å vise filnavnet. Men det står allerede i vindusteksten, så jeg fjerner den:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq doom-modeline-buffer-name nil)
#+end_src

Fjerner linje- og kolonnenummer: 
#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq doom-modeline-position-column-line-format '("%l"))
;; (setq doom-modeline-position-column-line-format nil)
#+end_src

Fjerner ikonet for visual/insert/normal state. Samme info står i echo area når man er utenfor normal mode, så den tilfører ingen ny info:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq doom-modeline-modal nil)
#+end_src


Fjerner bufferstørrelsen i kilobytes, nede til venstre:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! doom-modeline
  (remove-hook 'doom-modeline-mode-hook #'size-indication-mode))
#+end_src

Jeg prøvde først å bare sette ~(size-indication-mode -1)~, som fungerer fint om den evalueres direkte. Men under oppstart settes den tilbake i drift. Og derfor ble enden på visa å fjerne hook-en som ser ut til å kalle den slik det står ovenfor her. 


* Vim/evil og annen navigasjon

Alt som har med Vim-bevegelser og navigasjon å gjøre

** Fjerne uvaner

Et vanlig tips for å bli flinkere i Vim er å deaktivere ting som nybegynnere ofte klamrer seg til, for å tvinge overgang til bedre vaner. En av tingene er å bruke piltastene. Egentlig i det hele tatt, men spesielt i insert mode. Starter med å fjerne de akkurat i insert mode, hvor jeg ofte havner der

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! evil
  (defun my/deaktivere-piltaster ()
    (interactive)
    (message "Piltaster deaktivert."))

  (dolist (key '("<left>" "<right>" "<up>" "<down>"))
    (define-key evil-insert-state-map (kbd key) 'my/deaktivere-piltaster)
    (define-key evil-normal-state-map (kbd key) 'my/deaktivere-piltaster)
    )
  )
#+end_src
** Better-jumper

I ~Vim~ så funker ~``~ fint til å hoppe mellom ~evil-next-line~/~evil-previous-line~ når disse kalles med et tall, f.eks. ~5j~ eller ~10k~. Men ~evil-mode~ inkluderer ikke det.

Jeg brukte litt for mye tid til å prøve å vibe det til å virke, også ga jeg opp. Men jeg fant en løsning som heller bruker ~better-jumper~, som Doom har bundet til ~C-o~/~C-i~.

Boilerplate-koden nedenfor her er henta fra denne [[https://www.reddit.com/r/emacs/comments/1mztz6i/share_your_tips_for_fast_movements_and_navigation/][reddittråden]], også har jeg lagt til noen ekstra linjer under "jump scenarios" når jeg vil ha inn flere ting til å trigge et mark

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(use-package better-jumper

    :custom
    ; this is the key to avoiding conflict with evils jumping stuff
    (better-jumper-use-evil-jump-advice nil)

    :config
    (better-jumper-mode 1)

    ; this lets me toggle between two points. (adapted from evil-jump-backward-swap)
    (evil-define-motion better-jumper-toggle (count)
      (let ((pnt (point)))
        (better-jumper-jump-backward 1)
        (better-jumper-set-jump pnt)))

    ; this is the key here. This advice makes it so you only set a jump point
    ; if you move more than one line with whatever command you call. For example
    ; if you add this advice around evil-next-line, you will set a jump point
    ; if you do 10 j, but not if you just hit j. I did not write this code, I
    ; I found it a while back and updated it to work with better-jumper.
    (defun my-jump-advice (oldfun &rest args)
      (let ((old-pos (point)))
        (apply oldfun args)
        (when (> (abs (- (line-number-at-pos old-pos) (line-number-at-pos (point))))
                  1)
          (better-jumper-set-jump old-pos))))

    ; jump scenarios
    (advice-add 'evil-next-line :around #'my-jump-advice)
    (advice-add 'evil-previous-line :around #'my-jump-advice)
    (advice-add 'helm-swoop :around #'my-jump-advice)
    (advice-add 'evil-goto-definition :around #'my-jump-advice)
    (advice-add 'evil-goto-mark  :around #'my-jump-advice)
    (advice-add 'evil-avy-goto-char-2 :around #'my-jump-advice)
    )
    ; ... whenever you want a new jump scenario just use the above pattern.
#+end_src
** Hurtigtast - Markere til linjeslutt

Jeg markerer veldig okte til slutten av ei linje uten å ville ta med linjeskift. Lager en hotkey for det:

Med vimbindings kan man oppnå det med ~vg_~. Søkte opp hvilke funksjoner ~v~ og ~g_~ er bundet til, og la de inn i en egen funksjon nedenfor her.

Denne feiler om jeg legger den for høyt i configfila. Prøvde en times tid å finne ur hvorfor, før jeg ga opp og la den nederst her:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/visual-to-line-end ()
  (interactive)
  (evil-visual-char)
  (evil-last-non-blank))

(map! :leader
  (:prefix ("v" . "markering")
    :desc "Marker til linjeslutt"
    "g" #'my/visual-to-line-end))
#+end_src





* Utviklermiljø
** Parenteser

Aktiverer ~smartparens-mode~ overalt for å lyse opp motsats-parentesen til den jeg har markøren på:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(show-smartparens-global-mode 1)
#+end_src




* Åpne URL-er i Firefox på alle plattformer

Configen nedenfor gjør at jeg kan trykke på en URL og forvente at den åpnes i Firefox, i både WSL2 på Windows, i Android gjennom Termux, og på vanlig Linux.

Uten denne configen, så Emacs på Windows åpne URL-er i ~eww~-leseren hvis kjøres som ~.exe~, og ingensteds gjennom WSL. Og Android-klienten bare klager på at det mangler en innstilling og åpner ingenting.

Trikset er å utnytte ~system-type~ som returnerer ~gnu/linux~ i WSL og Linux, og ~android~ på Android. For å skille WSL fra Linux er det en ~and~ clause som i tillegg sjekker om miljøvariablene ~WSLENV~ er satt til noe, for det er den bare i WSL. Kunne sikkert kommet unna med å bare sjekke ~WSLENV~, men det funker slik det står. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! browse-url
  ;; Default to Firefox everywhere
  (setq browse-url-browser-function 'browse-url-generic)

  (cond
   ;; WSLENV fins bare på WSL, altså Windows
   ((and (eq system-type 'gnu/linux)
         (getenv "WSLENV"))
    (setq browse-url-generic-program "cmd.exe"
          browse-url-generic-args '("/c" "start" "")))

   ;; --- Linux ---
   ((eq system-type 'gnu/linux)
    (setq browse-url-generic-program "firefox"))

   ;; Android
   ((eq system-type 'android)
    (setq browse-url-generic-program "xdg-open"))))
#+end_src

- Detaljer om WSL-nettleserlinjene:
  - ~cmd.exe /c~: Kjør det som kommer etterpå i ~cmd.exe~.
  - ~start~: En Windows-builtin som sier at det som fôres inn til ~cmd~ skal åpnes med Windows' standardprogram for det
  - ~""~ trengs fordi den plasseringen i argumentrekkefølga er forbeholdt hva tittelen på toppen av programvinduet skal si. Flagget ignoreres vanligvis om det ikke gis inn, men en URL kommer inn med quotes, og uten en blank quote i forkant så tror windows at URL-en skal inn i vindustittelen
  - URL-en til slutt er URL-en som skal åpnes, som Windows nå skjønner at skal åpnes i standardnettleseren

* Android 
** Terminering av help-text
Help-text i minibufferen terminerer linjer som går utenfor skjermen. Det er visstnok for å bevare ting som meningsfull indentering i kodeeksempler.

Men på mobil er det kronglete å scrolle sidelengs, så jeg bytter til ~visual-line-mode~ i den situasjonen slik at lange setninger heller wrapper rundt


#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(when (eq system-type 'android)
    (add-hook 'help-mode-hook #'visual-line-mode))
#+end_src
** App-hurtigtaster

~am~ - Android Manager - på Termux kan snakke med Android sitt API og starte apper fra kommandolinja. Det kan Emacs bruke - her er en test som starter opp Gmail: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/android-launch-gmail ()
  "Launch the Gmail app"
      (interactive)
            (shell-command "am start -n com.google.android.gm/.ConversationListActivityGmail"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "l g" #'my/android-launch-gmail)
#+end_src
* WSL

Det er viktig å installere ~emacs-pgtk~ i stedet for ~emacs-gtk~.

Hvis man bare kjører ~sudo apt install emacs~, så får man sistnevnte, så man må eksplisitt installere ~pgtk~-versjonen.

Altså:

#+begin_quote
sudo apt install emacs-pgtk
#+end_quote


* Projectile

Legger til mapper jeg ofte søker gjennom

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! projectile
  (dolist (p '("~/repos/notater"
               "~/repos/ansible-desktop"))
    (projectile-add-known-project p)))
#+end_src

Bytter caching metode fra hybrid til alien, for at nye filer skal bli søkbare med en gang. Før jeg gjorde dette, måtte jeg kjøre ~projectile-invalidate-cache~ ofte for å få med nye filer

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq projectile-indexing-method 'alien)
#+end_src

Setter opp et advice som gjør at ~projectile-invalidate-cache~ kjøres etter hver ~rename-file~, slik at filer med nytt navn er automatisk søkbare i Projectile etter navneendring.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! projectile
  (defun my/rename-file-invalidate-projectile-cache (&rest _)
      (when (and (called-interactively-p 'any)
                       (featurep 'projectile))
                                     (projectile-invalidate-cache nil)))

  (advice-add 'rename-file :after #'my/rename-file-invalidate-projectile-cache))
#+end_src
    
* Org-mode
** Org-eksport

Setter noen verdier for å tilpasse info som inngår i eksport til HTML, PDF og lignende. Dette gir et minimum som er det jeg vanligvis trenger for å lime inn HTML til eposter og andre samarbeidsverktøy på jobb.

Også setter jeg ting som tittel, dato, TOC og lignende som ~#+OPTIONS~-verdier i hver enkelt fil om jeg faktisk skal lage en ekte artikkel som skal publiseres noe sted

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-export-with-date nil)
(setq org-export-with-author nil)
(setq org-export-with-title nil)
(setq org-export-with-toc nil)
(setq org-export-with-section-numbers nil)
(setq org-html-postamble nil) 
#+end_src

- ~org-html-postamble~ setter en blokk nederst i eksporten, med litt ulik info. Standarden er "author:/created:/validation:", basert på hva som fins av info. Fjerner hele greia med å sette den til ~nil~. 

** Org-ellipsis

~org~ viser i utgangspunktet fram ~[...]~ når tekst skjules under en headline. Gjør den litt mer minimal slik:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! org
  (setq org-ellipsis " ..."))
#+end_src

** Fjerne newlines mellom headere

Når man trykker ~TAB~ for å se headline-oversikten i en fil, så beholder org-mode en blank linje under alle headlines som har 2 eller flere newlines helt nederst. Det er ikke nyttig og ser stygt ut, så jeg fjerner det:

Det styres av ~setq org-cycle-separator-lines~, som har en veldig god forklaring om man inspect-er variabelen

løses ved å settte den til 0

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-cycle-separator-lines 0)
#+end_src

** Fargelegge TODO/DONE osv

Standard-fargene er ikke helt topp, så her er noen endringer:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! org
  (setq org-todo-keyword-faces
        '(;;("TODO" . (:foreground "#ffff00" :weight bold))
          ("STRT" . (:foreground "#ffff00" :weight bold))
          ("NEXT" . (:foreground "#ffffe0" :weight bold))
          ("KILL" . (:foreground "#595e60" :weight bold))
          ("WAIT" . (:foreground "#B4F8C8" :weight bold))
          ("HOLD" . (:foreground "#B4F8C8" :weight bold))
          ("PROJ" . (:foreground "#B4F8C8" :weight bold))
          ;;("DONE" . (:foreground "forest green" :weight bold))
          )))
#+end_src

#+RESULTS:

** CLOSED-property til TODO's
Denne setter opp en "CLOSED" timestamp når en oppgave markeres som DONE:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-log-done 'time)
#+end_src

#+RESULTS:
: time

** Egendefinert filnavn på nye org-filer

Org har sin egen måte å lage filnavn på, men jeg liker bedre standaradmåten sublimeless gjorde det på

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/datert-orgfil (title)
  "Create a new Org file with format YYYYMMDDMM Title.org in ~/repos/notater/."
  (interactive "sTitle: ")
  (let* ((timestamp (format-time-string "%Y%m%d%H%M"))
         (filename (format "~/repos/notater/%s %s.org" timestamp title)))
    (find-file filename)))
#+end_src

#+RESULTS:
: my/datert-orgfil

** Org-directory

Forteller Emacs/org-mode hvor det skal letes etter ~.org~-filer:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-directory (expand-file-name "~/repos/notater/"))

(setq org-roam-directory org-directory)
(after! org-roam
  (org-roam-db-autosync-mode))
#+end_src

** Org-capture templates

Org-capture gjør at man kan få skrevet inn smånotater til en fil uten å måtte åpne filen.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! org
  (let ((innboks      "~/repos/notater/202012111337 Innboks.org")
        (innboks-jobb "~/repos/notater/202111121500 Innboks jobb.org")
        (hodepine     "~/repos/notater/202205082206 Hodepinelogg.org")
        (familie      "~/repos/notater/org/20250531191654-todo_familie.org")
        (personlig    "~/repos/notater/202506120825 Todo.org"))

    (setq org-capture-templates
          `(
            ("i" "Innboks" plain
             (file ,innboks)
             "%^{Notat}\n" :prepend t :immediate-finish t :empty-lines 1)
            ("j" "Innboks-jobb" plain
             (file ,innboks-jobb)
             "%^{Notat}\n" :prepend t :immediate-finish t :empty-lines 1)
            ("f" "Todo familie" entry
             (file+headline ,familie "Senere")
             "** TODO %^{Oppgave}\n" :prepend t :immediate-finish t)
            ("4" "Todo familie i dag" entry
             (file+headline ,familie "På gang")
             "** TODO %^{Oppgave}\nSCHEDULED: %t\n" :prepend t :immediate-finish t)
            ("5" "Personlig" entry
             (file+headline ,personlig "Senere")
             "** TODO %^{Oppgave}\n" :prepend t :immediate-finish t)
            ("t" "Todo personlig i dag" entry
             (file+headline ,personlig "På gang")
             "** TODO %^{Oppgave}\nSCHEDULED: %t\n" :prepend t :immediate-finish t)
            ("h" "Hodepine" plain
             (file+headline ,hodepine "Logg")
             "%<%Y-%m-%d %H:%M:%S %a> - %^{Intensitet (1-10)}\n" :prepend t :immediate-finish t)
            ))))
#+end_src


- ~:immediate-finish t~ gjør at teksten bare lagres i buffer uten at man blir bedt om å dobbeltsjekke resultatet i en visningbuffer
- ~file+headline~ sier at teksten skal skrives inn i filen som oppgis først, og under headline-en som oppgis etterpå. F.eks. ~Logg~ her
- 

** toc-org

toc-org het opprinnelig org-toc, men så var det noe navnekonflikter som førte til navnebytte. Men begge referanser fins fortsatt på internett, som gjør at LLM-er refererer til begge deler når man spør om hjelp.

Denne linja gjør at innholdsfortegnelser tar med statuser som TODO/STRT/DONE o.l., i stedet for standardsettingen som er å ignorere de

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-export-with-todo-keywords t)
#+end_src
** ~NEXT~-status 

Legger til en ~NEXT~-status oppå Doom sine defaults:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! org
  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "PROJ(p)" "LOOP(r)" "STRT(s)" "WAIT(w)" "HOLD(h)" "IDEA(i)"
                    "|" "DONE(d)" "KILL(k)")
          (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")
          (sequence "|" "OKAY(o)" "YES(y)" "NO(N)"))))
#+end_src

Inspirert av Bastien Guerry sin [[https://bzg.fr/en/the-zen-of-task-management-with-org/][The Zen of Task Management with Org]]

* Org-agenda
** Sortering

[[https://orgmode.org/manual/Sorting-of-agenda-items.html][Standard sortering]] er at schedules med klokkeslett kommer aller først, deretter listes TODO-ene i grupper etter hvilken fil ("category") de kommer fra. Innad i hver kategori brukes priority cookies, og til slutt hvorvidt ting er forsinka eller har en deadline som er utgått

** Global agendaconfig
Fjerner visning av tags og filnavn

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-agenda-remove-tags t)
#+end_src

Så fjerner jeg alt fra ~org-agenda-prefix-format~. Spesielt ~search~-delen gjør at jeg slipper å se filbanen til hver TODO. Resten gjør ingenting såvidt jeg forstår, så jeg starter like greit med et blankt utgangspunkt og tilpasser det fra scratch:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-agenda-prefix-format
      '((agenda . "")
        (todo . "")
        (tags . "")
        (search . "")))
#+end_src

Fjerner helpteksten øverst i agendaen. Default melding før jeg fjerna den var dette:

#+begin_quote
Headlines with TAGS match: sprint
Press ‘C-u r’ to search again
#+end_quote

Fjerner de og erstatter alt med ~" "~. SPC-tegnet gjør at jeg setter inn en blank linje helt på topp, for å få litt margin.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-agenda-overriding-header " ")
#+end_src
** Visning av antall dager og startdag

Default er å vise 10 dager med ~org-agenda-span~, med oppstart for tre dager siden vha. ~org-agenda-start-day~, slik at man ser tre dager  bak og syv dager fram. 

Setter default til å bare vise dagen i dag: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! org-agenda
  (setq org-agenda-start-day nil)
  (setq org-agenda-span 1)
  (setq calendar-week-start-day 1)
  )
#+end_src

~calendar-week-start-day~ gjelder visningen av kalender i f.eks. ~org-schedule~, som starter på søndag isf. mandag om man ikke setter den til ~1~

** Separere daglig repeterende oppgaver fra alt annet 

Jeg har en liste med daglige småting jeg vil få gjort, og det er fint å få den skilt ut fra de større, viktigere oppgavene jeg setter opp til egne dager.

Her er et stykke vibekode fra Claude som setter opp to filterfunksjoner + et agenda-view som bruker de. Da får jeg to agendaer over hverandre - en for repeterende TODOs og en for ikke-repeterende. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/skip-recurring ()
  "Skip entries with repeating timestamps."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (save-excursion
          (re-search-forward "<[^>]*\\+[0-9]+[dwmy][^>]*>" subtree-end t))
        subtree-end
      nil)))

(defun my/skip-non-recurring ()
  "Skip entries WITHOUT repeating timestamps."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (save-excursion
          (re-search-forward "<[^>]*\\+[0-9]+[dwmy][^>]*>" subtree-end t))
        nil
      subtree-end)))


(setq org-agenda-custom-commands
      '(
        ("d" "Daily"
         ((agenda ""
                  ((org-agenda-span 'day)
                   (org-agenda-skip-function '(my/skip-recurring))
                   (org-agenda-overriding-header " ")))
          (agenda ""
                  ((org-agenda-span 'day)
                   (org-agenda-skip-function '(my/skip-non-recurring))
                   (org-agenda-overriding-header "\nDaglig")))))))

#+end_src
** Hurtigtaster

Dooms default for å kalle ~org-agenda~ er ~SPC o A~, som er litt for langt. Setter den til ~SPC A~:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "A" #'org-agenda)
#+end_src


** Fjerne visning av repeterende oppgaver

Man kan schedule TODO's til å repetere seg daglig, som er nyttig til sånne små morgenrutine-ting man f.eks. gjør hver morgen på jobb.

Men de fyller opp agendavisningen med støy, så jeg deaktiverer visning av repetisjonene. Slik at repeterende oppgaver kun vises på neste kommende dato:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-agenda-show-future-repeats nil)
#+end_src
** Fjern dimming av "blokkerte" oppgaver

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-agenda-dim-blocked-tasks nil)
#+end_src

En TODO ansees angivelig som "blokkert" når jeg fjerner nedstrøms oppgaver fra visningen, og da får den dimmed farge. Det vil jeg ikke, og det kan løses med å disable dimming i agendaview med å sette denne til ~nil~.

* Org-babel
** Generelle eksport-innstillinger

~_~-tegn i URL-er kan finne på å gjøre at lenker blir eksportert feil, med alt etter ~_~ som subscript. Denne linja fjerner subscript i all eksport, som sannsynligvis er overkill. Men fungerer fint enn så lenge:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-export-with-sub-superscripts nil)
#+end_src

Inkludere linjeskift: Org og Markdown er glade i å ignorere enkle linjeskift, sånn at eksempelvis

#+begin_src conf
Linje 1
Linje 2
#+end_src

Eksporteres som

#+begin_src conf
Linje 1Linje 2
#+end_src

For meg er det naturlig å beholde slike linjeskift i all eksport, så jeg setter den endringen slik:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq org-export-preserve-breaks t)
#+end_src

Om man vil ha det tilbake i enkeltfiler, så kan man legge til:

#+begin_src org
#+OPTIONS: \n:t
#+end_src


** Ansible-støtte

~org-babel~ støtter ikke Ansible-kode ut fra boksen, men det kan legges til med ~ob-ansible.el~. Jeg klarte ikke finne på en smart måte å legge den til, så jeg lasta ned ob-ansible fra Github og kopierte kildekoden rett inn i ~/dotfiler/doom/lokal/ob-ansible.el~, og ~require~-er den inn derfra. Så jeg har en frossen kopi av akkurat denne pakka. Antar jeg la til den ´add-load-path´-setningen først for å få Emacs til å lete etter ~ob-ansible~ i riktig mappe

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el

(add-load-path! "~/.config/doom/lokal")

(after! org
  (require 'ob-ansible)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ansible . t)  
     )))
#+end_src

** Eksport til HTML
Hjemmesnekra alternativ til ~org-export-to-html~, som eksporterer til ~/tmp~ i stedet for den versjonskontrollerte mappa jeg vanligvis er i. Også åpner den automatisk fila i nettleser. Den sender samtidig hele output-et rett til utklippstavla

~browse-url~ har jeg moddet [[*Åpne URL-er i Firefox på alle plattformer][her]], sånn at den åpner i nettleser på tvers av WSL, Linux og Android

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/org-eksport-to-tmp-html ()
  (interactive)
  (let ((outfile (concat "/tmp/"
                         (file-name-base (or (buffer-file-name)
                                             (buffer-name)))
                         ".html")))
    ;; Eksporterer til HTML til en outfile-variabel
    (org-export-to-file 'html outfile nil nil nil nil nil)
    ;; Kopierer til utklippstavla
    (call-process-shell-command
     (format "xclip -selection clipboard -t text/html < %s"
             (shell-quote-argument outfile)))
    ;; Åpner i nettleser
    (browse-url (if (and (eq system-type 'gnu/linux)
                         (getenv "WSLENV"))
                    (concat "\\\\wsl.localhost\\Ubuntu" outfile)
                  outfile))))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "e h" #'my/org-eksport-to-tmp-html)
#+end_src


** Eksport til PDF

Dette er den vanlige eksportfunksjonen ~org-latex-export-to-pdf~, pluss...

- Tittel er toppnivå headline i valgt tekst, i stedet for filnavnet
- PDF-en åpnes automatisk i nettleser med ~browse-url~ som jeg har moddet tidligere til å virke bra på alle OS-plattformer

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/org-eksport-til-pdf ()
  "Export subtree using headline as title and open in browser."
  (interactive)
  (org-back-to-heading t)
  (let* ((title (nth 4 (org-heading-components)))
         (pdf-file (progn
                     (org-set-property "EXPORT_TITLE" title)
                     (org-latex-export-to-pdf nil t))))
    (when pdf-file
      (browse-url pdf-file))))
#+end_src

** noeksport = notangle

~:noexport:~-taggen gjør at alt nedstrøms headline blir ignorert når man eksporterer til PDF/HTML og andre formater. Mem den har i utgangspunktet ingenting med tangling til konfigfil å gjøre.

Her legger jeg inn et advice på ~org-babel-tangle-single-block~-funksjonen, og ber den ignorere alle kodeblokker nedstrøms en :noexport:-tagg.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(advice-add 'org-babel-tangle-single-block :before-while
            (lambda (&rest _)
                          (not (member "noexport" (org-get-tags)))))
#+end_src

* Org-bullets

Gjør headerpunkter finere. Prøvde opprinnelig ~org-modern~, men det inneholdt så mye annet rart som ikke funket så bra med temaet jeg har. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! org-bullets)
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! org
  (add-hook 'org-mode-hook #'org-bullets-mode))
#+end_src


* Org-transclusion

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! org-transclusion)
#+end_src
* Yasnippet

Yasnippet har en tendens til å indentere den siste linja for å matche indentering i kodeblokken som wrappes. Det gjør at ~end_src~ ender opp slik:

Fant et råd i et gammelt [[https://github.com/syl20bnr/spacemacs/issues/9822#issuecomment-730284330][GitHub-issue]] at jeg kan fjerne den oppførselen med å sette ~yas-indent-line~ til ~fixed~:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(add-hook 'org-mode-hook
          (lambda () (setq-local yas-indent-line 'fixed)))
#+end_src

* Markdown

Her er noen kodeblokker for å gjøre visning av markdownfiler mye bedre. Alt her er stjålet rett fra Reddit-tråden [[https://www.reddit.com/r/emacs/comments/10h9jf0/beautify_markdown_on_emacs/][Beautify markdown on emacs]]:

Først noen linjer for å gjøre headerne større og mer utprega: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(custom-set-faces!
  '(markdown-header-delimiter-face :foreground "#616161" :height 0.9)
  '(markdown-header-face-1 :height 1.8 :foreground "#A3BE8C" :weight extra-bold :inherit markdown-header-face)
  '(markdown-header-face-2 :height 1.4 :foreground "#EBCB8B" :weight extra-bold :inherit markdown-header-face)
  '(markdown-header-face-3 :height 1.2 :foreground "#D08770" :weight extra-bold :inherit markdown-header-face)
  '(markdown-header-face-4 :height 1.15 :foreground "#BF616A" :weight bold :inherit markdown-header-face)
  '(markdown-header-face-5 :height 1.1 :foreground "#b48ead" :weight bold :inherit markdown-header-face)
  '(markdown-header-face-6 :height 1.05 :foreground "#5e81ac" :weight semi-bold :inherit markdown-header-face))
#+end_src

Så er det en håndfull elispfunksjoner som disabler den markdown-rendering på akkurat den linja man er på, sånn at det fortsatt er lett å redigere markupen

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
 (defvar nb/current-line '(0 . 0)
   "(start . end) of current line in current buffer")
 (make-variable-buffer-local 'nb/current-line)

 (defun nb/unhide-current-line (limit)
   "Font-lock function"
   (let ((start (max (point) (car nb/current-line)))
         (end (min limit (cdr nb/current-line))))
     (when (< start end)
       (remove-text-properties start end
                       '(invisible t display "" composition ""))
       (goto-char limit)
       t)))

 (defun nb/refontify-on-linemove ()
   "Post-command-hook"
   (let* ((start (line-beginning-position))
          (end (line-beginning-position 2))
          (needs-update (not (equal start (car nb/current-line)))))
     (setq nb/current-line (cons start end))
     (when needs-update
       (font-lock-fontify-block 3))))

 (defun nb/markdown-unhighlight ()
   "Enable markdown concealling"
   (interactive)
   (markdown-toggle-markup-hiding 'toggle)
   (font-lock-add-keywords nil '((nb/unhide-current-line)) t)
   (add-hook 'post-command-hook #'nb/refontify-on-linemove nil t))

#+end_src

Til slutt en hook for å aktivere alle funksjonene ovenfor når jeg er i en Markdown-fil:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
 (add-hook 'markdown-mode-hook #'nb/markdown-unhighlight)
#+end_src


* Workspaces

Setter opp et utvalg workspaces sånn at jeg raskt kan dra fram de vanligste filene jeg vil endre innenfor samme kontekst.

De fleste workspace-ene inneholder delvis sensitive filnavn o.l. pga jobb, så de defineres opp i en egen ~.emacs.secrets~-fil som importeres tidligere i denne config-en. Men de følger samme mal som dette Emacs-config-workspacet:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/workspace-emacs-config ()
  "doom-config + literalfilen de utgår fra"
  (interactive)
  (+workspace/new "emacs-config")
  (find-file "~/repos/dotfiler/doom/config.el")
  (find-file "~/repos/dotfiler/doom/init.el")
  (find-file "~/repos/dotfiler/doom/packages.el")
  (find-file "~/repos/dotfiler/emacs-config.org")
  (let ((optional-file "~/.emacs.secrets"))
    (when (file-exists-p optional-file)
      (find-file optional-file)))
  (switch-to-buffer "config.el")
  )
#+end_src






Mal:


#+begin_src emacs-lisp
(defun my/workspace-NAVN ()
  "doom-config + literalfilen de utgår fra"
  (interactive)
  (+workspace/new "NAVN"
  (find-file "")
  (find-file "")
  (find-file "")
  (find-file "")
  )
#+end_src

Dette kunne vært skrevet smartere vha. makroer, parameterisering og så videre. Men det funker fint slik det står 

* Writeroom

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq writeroom-width 50)
#+end_src

* Embark

Aka "action menu super buffer". Det er den som popper opp når man har tastet en halv hotkey, og Emacs venter på neste tast. Da ser man alle alternativer. Embark legger til fuzzy search av actions, så jeg slipper å lese gjennom actionlista hver gang i forsøk på å finne ting. Ulempen er at jeg -må- skrive kommandonavnet i stedet for å bruke en hotkey, men tror det er best nå

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq embark-prompter 'embark-completing-read-prompter)
#+end_src

* Hurtiglenker til nettsider
** Epost
Åpne Gmail- og Outlook-innboksene fra Emacs:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/open-gmail-firefox-tab ()
  "Åpner Gmail som ny tab i Firefox"
  (interactive)
  (browse-url
   "https://mail.google.com/mail/u/0/#inbox"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/open-outlook-firefox-tab ()
  "Åpner Outlook som ny tab i Firefox"
  (interactive)
  (browse-url "https://outlook.office.com/mail/"))
#+end_src

** Værmeldinger
*** my/yr-lillebo

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/yr-lillebo ()
  "Open the weather forecast for Lillebo in the system’s default browser."
  (interactive)
  (browse-url
  "https://www.yr.no/nb/v%C3%A6rvarsel/daglig-tabell/1-174419/Norge/Innlandet/Engerdal/Lillebo"))
#+end_src

*** my/yr-innbygda
#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/yr-innbygda ()
  "Værmelding for Innbygda"
  (interactive)
  (browse-url "https://www.yr.no/nb/v%C3%A6rvarsel/daglig-tabell/1-157692/Norge/Innlandet/Trysil/Innbygda"))
#+end_src

*** my/yr-oslo-christies
#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/yr-oslo-christies ()
  "Værmelding for Oslo"
  (interactive)
  (browse-url "https://www.yr.no/nb/v%C3%A6rvarsel/daglig-tabell/10-995776/Norge/Oslo/Oslo/Christies%20gate"))
#+end_src
*** Hurtigtast til alle værmeldinger

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("y" . "yr")
       :desc "Lillebo"  "l" #'my/yr-lillebo
       :desc "Innbygda" "i" #'my/yr-innbygda
       :desc "Oslo"     "o" #'my/yr-oslo-christies))
#+end_src

** Kalender
*** Google

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/open-google-kalender-firefox-tab ()
  "Åpner Google Calendar som ny tab i Firefox"
  (interactive)
  (browse-url "https://calendar.google.com/"))
#+end_src

*** Outlook

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/open-outlook-kalender-firefox-tab ()
  "Åpner Outlook Calendar som ny tab i Firefox"
  (interactive)
  (browse-url "https://outlook.office.com/calendar/view/week"))
#+end_src

* Magit
** ~magit-list-repositories~

Dette er dashboardet som viser alle repoer i en felles visning.

Før den kan brukes, må man sette en path til hvor alle repoene ligger. Jeg bruker:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq magit-repository-directories
      `((,my/søkesti . 1)))
#+end_src

*** Kolonner med info

Dette er config for kolonnene som skal vises, som er standard-kolonnene pluss ~Flag~ som viser status på staged/unstaged, ~Branch~ som viser branchnavn

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq magit-repolist-columns
      '(("Name"    25 magit-repolist-column-ident nil)
        ("B<U"      3 magit-repolist-column-unpulled-from-upstream nil)
        ("B>U"      3 magit-repolist-column-unpushed-to-upstream nil)
        ("Flag"     4 magit-repolist-column-flag nil)
        ("Branch"  20 magit-repolist-column-branch nil)
        ("Path"    99 magit-repolist-column-path nil)))
#+end_src

** Hotkey: Autocommit med Magit

Jeg committer vanligvis notater med "NN " etterfulgt av my/tidsstempel-sekund.

Det er fortsatt litt for mange steg på en mobiltelefon, så jeg automatiserer det fram til commitsteget her:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/notatcommit ()
  (interactive)
  (magit-stage-modified)
  (magit-commit-create (list "-m" (concat "NN " (format-time-string "%Y-%m-%d %H:%M:%S")))))
#+end_src

Setter opp hotkey så den kan kjøres med ~SPC g n~:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "g n" #'my/notatcommit)
#+end_src
** Hotkey: git pull & git pull

pull:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "g p" #'magit-pull-from-pushremote)
#+end_src

push: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "g P" #'magit-push-current-to-pushremote)
#+end_src
** Legger til authinfo-login
Noen steder må jeg bruke HTTPS i stedet for SSH-autentisering. Da kan jeg legge GitHub-token-et til ~.authinfo~-filen jeg har separat, og peke Magit til den slik for å slippe å måtte oppgi token hver gang:


#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! magit
  (add-hook 'magit-process-find-password-functions
            'magit-process-password-auth-source))
#+end_src



* Små funksjoner og hurtigtaster
** Slett alle nummererte linjer

Innlimt tekst fra programmer med linjenumre ender i noen tilfeller opp med alle linjenumrene kommer på egne linjer. Her er vibekodet funksjon til å slette alle sammen i markert område:


#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/slett-nummerlinjer (start end)
  "Slett linjer som kun har et nummer i seg, i markert område"
  (interactive "r")
  (save-excursion
    (save-restriction
      (narrow-to-region start end)
      (goto-char (point-min))
      (while (not (eobp))
        (if (looking-at "^[[:space:]]*[0-9]+[[:space:]]*$")
            (delete-region (line-beginning-position)
                          (min (1+ (line-end-position)) (point-max)))
          (forward-line 1))))))
#+end_src


** Markdown-lenker -> Org-lenke

Oversetter lenker fra ~[]()~ til ~[[][]]~ med innhold

regex-en er vibbekoda med Claude. Før regex-en er det noen linjer for å få plassert markøren på rett plass

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/markdown-lenke-til-org ()
  (interactive)
  (beginning-of-line)
  (search-forward "[")
  (backward-char)
  (when (looking-at "\\[\\([^]]+\\)\\](\\([^)]+\\))")
    (replace-match "[[\\2][\\1]]")))
#+end_src

** Funksjon for å skrive YYYY-MM-DD-TT-MM

Jeg skriver ofte tidsstempler, så her er to custom funksjoner for å til det med en hotkey

To funksjoner for hhv. ~YYYY-MM-DD TT:MM:SS~ og kun ~YYYY-MM-DD~:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/tidsstempel-sekund ()
  "Returnerer tidsstempel som YYYY-MM-DD TT:MM:SS"
  (interactive)
  (insert (format-time-string "%Y-%m-%d %H:%M:%S")))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/tidsstempel-dato ()
  "Returnerer tidsstempel som YYYY-MM-DD"
  (interactive)
  (insert (format-time-string "%Y-%m-%d")))
#+end_src

Så binder jeg de opp mot hver sin hotkey:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! "<S-delete>" #'my/tidsstempel-dato)
(map! "<C-S-delete>" #'my/tidsstempel-sekund)
#+end_src

** Ukenummer til echo area

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/ukenummer ()
  (interactive)
  (let ((now (current-time)))
    (message "Uke %s" (format-time-string "%V" now))))
#+end_src

** Måle tidsbruk på evaluering

Denne er stjålet [[https://github.com/cloudstreet-dev/Emacs-for-Goodness-Sake/blob/main/04-configuration.md][herfra]]. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defmacro measure-time (&rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (message "%.06f seconds"
              (float-time (time-since time)))))
#+end_src

Eksempel på bruk:

#+begin_src elisp
(measure-time (sleep-for 5))
#+end_src

Resultat:

#+begin_quote
#+RESULTS:
: 5.000108 seconds
#+end_quote

** Legge inn debugprint i *Messages*-bufferen
:PROPERTIES:
:EXPORT_TITLE: Linjeskift/debugprint i *Messages*-bufferen
:END:

For å lage luft, og se hvor noe starter og noe annet slutter

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/message-debugprint()
  (interactive)
  (message "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
  (message "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
  (message "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"))
#+end_src
** my/todo-i-dag

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/todo-i-dag (title)
  "Insert a new TODO heading scheduled for today."
  (interactive "sTODO title: ")
  (org-insert-heading)
  (insert "TODO " title)
  (org-schedule nil (format-time-string "%Y-%m-%d")))
#+end_src


** my/wrap-med-src-conf

Jeg rammer veldig ofte inn kode- og config-blokker i en ~begin_src conf~-blokk, så dette gjør det automagisk med ett funksjonskall. Og flytter markøren til å ligge to newlines under blokken, som er der jeg vanligvis vil fortsette fra:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/wrap-med-src-conf ()
  "Rammer inn tekstblokk i en #+begin_src conf block"
  (interactive)
  (let ((bounds (bounds-of-thing-at-point 'paragraph)))
    (when bounds
      (goto-char (cdr bounds))
      (skip-chars-backward " \t\n" (car bounds))
      (let ((end (point)))
        (goto-char (car bounds))
        (skip-chars-forward " \t\n" end)
        (let ((beg (line-beginning-position)))
          (goto-char end)
          (end-of-line)
          (delete-region (point) (cdr bounds))
          (insert "\n#+end_src\n\n")
          (let ((target (point-marker)))
            (goto-char beg)
            (delete-region (car bounds) beg)
            (insert "\n#+begin_src conf\n")
            (goto-char target)
            (set-marker target nil)))))))
#+end_src

Hotkey:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "i w" #'my/wrap-med-src-conf)
#+end_src

** my/sjekkboks

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/sjekkboks ()
  ""
  (interactive)
  (insert "- [ ] "))
#+end_src

Hotkey:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "-" #'my/sjekkboks)
#+end_src



* Dirvish
** Hotkeys
Dirvish sin hurtigmeny er bedre enn bookmarks-funksjonen til Emacs, så jeg overstyrer ~SPC RET~ hurtigtasten for det her:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      :desc "Dirvish quick access"
      "RET" #'dirvish-quick-access)
#+end_src

Har ikke funnet noen hotkey for å hoppe til home. Lager den selv og binder den til tilde:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :map dirvish-mode-map
      :n "~" (lambda () (interactive) (dired "~/")))
#+end_src

Skifter ut ~SPC o /~ for å åpne filutforskeren med ~SPC o o~, for å passe bedre med norsk tastatur:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("o" . "open")
       :desc "Open Dirvish (alias SPC o /)" "o" #'dirvish))
#+end_src

** ~dirvish-quick-access-entries~
I ~dirvish-quick-access-entries~ kan man liste opp snarveier til filer man bruker ofte, også kan man hente de raskt ut med ~SPC RET .~. Lista mi inneholder referanser til jobb og fritid, så selve lista er definert i ~.emacs.secrets~ og importeres hit under [[*Secrets][Secrets]]-headeren. Også binder denne elisp-snutten lista opp mot Dirvish

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! dirvish
  (when (boundp 'my/dirvish-snarveier)
    (setq dirvish-quick-access-entries my/dirvish-snarveier)))
#+end_src

** TRAMP-tilpasning
Uten å være helt sikker, så tror jeg preview-funksjonen til Dirvish får SSH-sesjoner med TRAMP til å fryse Emacs. Disabler slik:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(after! dirvish
  (setq dirvish-tramp-preview-disabled t))
#+end_src



* Blamer.el - inline git blame

Tilsvarende GitLens fra VSCode 

Bruker ~blamer.el~: https://github.com/Artawower/blamer.el

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! blamer)
#+end_src

Utgangspunktet er kopi-pasta rett fra README-en

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(use-package blamer
  :bind (("s-i" . blamer-show-commit-info))
  :defer 20
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 70)
  :custom-face
  (blamer-face ((t :foreground "#7a88cf"
                    :background unspecified
                    :height 140
                    :italic t)))
  :config
  (global-blamer-mode 0))
#+end_src

* Startside

Setter Emacs til å starte opp i et generisk innboksnotat.

~unless~-linja er der fordi jeg av og til har en jobbrelatert fil som oppstartsbuffer. Den settes i så fall i en ~.secrets~-fil som lastes tidligere. 

Så lenge jeg bruker Doom Emacs, så er ~initial-buffer-choice~ satt til symbolet ~doom-fallback-buffer~ med mindre jeg har satt den til noe annet. "Noe annet" vil i så fall være en filbane i plaintext. Derfor sjekker jeg om ~initial-buffer-choice~ er en string, og hvis den ikke er det, da setter jeg den til standardfilen nedenfor

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(unless (stringp initial-buffer-choice)
  (setq initial-buffer-choice (lambda () (org-agenda nil "d") (current-buffer))))
#+end_src



* Nettradio med EMMS

Prøvde opprinnelig å få radiostasjoner inn i ~emms-streams~-lista, men jeg ga opp. Jeg endte opp med å vibe-kode en egen måte å legge inn radiostasjoner på. Det har fungert fint å bare sette opp en egen funksjon for hver radiokanal, sånn at jeg kan starte hver radio med ~M-x kanalnavn~ eller en hotkey. 

NRK-lenkene er henta herfra: https://lyd.nrk.no/. 

** Installere EMMS og MPV

Installerer ~emms~:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! emms :recipe (:host github :repo "emacsmirror/emms"))
#+end_src

I utgangspunktet kunne jeg bare avkommentert ~emms~ fra ~init.el~-filen, også hadde Doom-rammeverket installert det automagisk. Men det har vist seg å være ustabilt, fordi standardserveren som hoster ~emms~ er under press og svarer ikke regelmessig. Derfor ber jeg om å hente ~emms~ fra https://github.com/emacsmirror/emms i stedet for http://savannah.gnu.org/, som er standard. 

Når det er installert kan jeg be om å ta i bruk pakka, og peke på en mediaspiller som skal brukes til å spille av lyd. Her er det [[https://mpv.io/][mpv]] som brukes. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(use-package emms
  :defer t
  :config
  (emms-minimalistic)
  (setq emms-player-list '(emms-player-mpv)))
#+end_src

** Hurtigtast: Stoppe radioen
Mapper ~emms-stop~ til ~SPC e s~:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "Stopp EMMS" "s" #'emms-stop))
#+end_src

** Hvordan hente ut stream-URLs
Noen nettradioer skjuler stream-URL-en. Da kan man ofte få tak i den slik:

1) I Firefox: Ctrl+Shift+C for å få opp developer tools
2) Velg ~Network~
3) Filtrer på "media" hvis det er mye støy
4) Se etter noe som slutter på ~.mp3~, ~.aac~, ~.m3u~ eller lignende
5) Hvis det ikke er noe, kan man skru radioen av og på for å trigge en ny GET-request

** DEFCON

[[https://somafm.com/player24/station/defcon][soma fm - DEF CON Radio]]

Legger inn stream URL: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-defcon ()
  "Spiller av DEF CON Radio"
  (interactive)
  (emms-play-url "http://ice3.somafm.com/defcon-128-mp3"))
#+end_src

Hurtigtast:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "DEF CON" "d" #'my/radio-defcon))
#+end_src

** NRK P1

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-p1 ()
  "Spiller av NRK P1"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/p1_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK P1" "1" #'my/radio-nrk-p1))
#+end_src

** NRK P2

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-p2 ()
  "Spiller av NRK P2"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/p2_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK P2" "2" #'my/radio-nrk-p2))
#+end_src

** NRK P3

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-p3 ()
  "Spiller av NRK P3"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/p3_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK P3" "3" #'my/radio-nrk-p3))
#+end_src

** NRK P13

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-p13 ()
  "Spiller av NRK P13"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/p13_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK P13" "t" #'my/radio-nrk-p13))
#+end_src

** NRK mP3

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-mp3 ()
  "Spiller av NRK mP3"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/mp3_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK mP3" "m" #'my/radio-nrk-mp3))
#+end_src

** Cinemix

Filmusikk. Herfra: https://www.cinemix.us/

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-cinemix ()
  "Spiller av Cinemix sin nettradio - Filmmusikk"
  (interactive)
  (emms-play-url "https://kathy.torontocast.com:1190/stream"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "Cinemix" "c" #'my/radio-cinemix))
#+end_src
** NRK Jazz

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-jazz ()
  "Spiller av NRK Jazz"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/jazz_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK Jazz" "j" #'my/radio-nrk-jazz))
#+end_src
** Rainwave

Videospillmusikk. Herfra: https://rainwave.cc//

De har fem ulike kanaler: Chiptune, "games", oc remix, og covers. Denne kanalen er "all", som henter litt fra alle fire

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-rainwave ()
  "Spiller av Rainwave.cc sin nettradio - Videospillmusikk"
  (interactive)
  (emms-play-url "https://relay.rainwave.cc/all.mp3"))

#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "Rainwave" "r" #'my/radio-rainwave))
#+end_src

** ChilledCow

Nettside: https://liveonlineradio.net/chilledcow

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-chilledcow ()
  "Spiller av ChilledCow radio"
  (interactive)
  (emms-play-url "https://ilm.stream35.radiohost.de/ilm_ilovechillhop_mp3-192"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "ChilledCow" "x" #'my/radio-chilledcow))
#+end_src
** NRK Klassisk

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-nrk-klassisk ()
  "Spiller av NRK Klasisk"
  (interactive)
  (emms-play-url "https://cdn0-47115-liveicecast0.dna.contentdelivery.net/klassisk_mp3_h"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "NRK Klassisk" "k" #'my/radio-nrk-klassisk))
#+end_src

** Asteroid Radio

https://asteroid.radio/


#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-asteroid ()
  "Spiller av Asteroid Radio"
  (interactive)
  (emms-play-url "http://ice.asteroid.radio/asteroid.aac"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "Asteroid Radio" "a" #'my/radio-asteroid))
#+end_src



** Freecodecamp radio

https://coderadio.freecodecamp.org/

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-freecodecamp ()
  "Spiller av freeCodeCamp sin nettradio"
  (interactive)
  (emms-play-url "https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3"))

#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "FreeCodeCamp" "f" #'my/radio-freecodecamp))
#+end_src

** Radio Pays de Guéret

Fransk [[https://www.radiopaysdegueret.fr/][nettradio]] som spiller veldig variert musikk

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defun my/radio-pays-de-gueret ()
  "Spiller av Radio Pays de Gueret - Misc. fransk++"
  (interactive)
  (emms-play-url "https://radiopaysdegueret.ice.infomaniak.ch/radiopaysdegueret.mp3"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      (:prefix ("e" . "emms")
       :desc "Pays de Guéret" "p" #'my/radio-pays-de-gueret))
#+end_src

* gptel
** Installering og aktivering

Installerer gptel-pakka:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! gptel :recipe (:nonrecursive t))
#+end_src

Aktiverer den i Emacs:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(use-package! gptel)
#+end_src

Binder opp ~gptel-send~ og ~gptel-menu~ til hver sin hotkey:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(map! :leader
      "t s" #'gptel-send
      "t m" #'gptel-menu)
#+end_src

** System prompt

Ofte kalt "personalisering"-parameteren. Det er den teksten som mates inn i forkant av hver request, for å tilpasse oppførselen til AI-en.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defvar gptel-systemmelding
  "Please keep it short and to the point.

Use bullet points when that can make complex matter easier to read.

Do not start sentences with compliments and phrases like \"aha, good question\" - just reply without this emphasis.

Do not engage in any form of flattery or syncophancy.

Assume I misunderstand basic facts from time to time, and try to make me aware of this

If I send you this and nothing else: \"foobar\", then reply only with the word \"baz\".

Actively try to prove me wrong

Recommend a book from time to time. Always double check that any book mentioned exists in real life

Always reply in English even though I ask you questions in Norwegian, unless specifically asked to reply in Norwegian

Avoid filler text. It is OK if that makes the responses look \"cold\" or detached")
#+end_src

Lager en preset i gptel-configen her:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(gptel-make-preset 'standard-test
  :system gptel-systemmelding)
#+end_src

Setter den som standard ved boot:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(gptel--apply-preset 'standard-test)
#+end_src

Noen ganger har jeg lurt på om systemmeldingen i det hele tatt blir lest og tatt i bruk. Da har jeg byttet til ~emoji-preset~ nedenfor her som et debugging-verktøy, for da blir det ganske åpenbart om AI-en følger instruksen eller ikke

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(defvar gptel-emojitest "only reply with emojis and nothing else")

(gptel-make-preset 'emoji-preset
  :system gptel-emojitest)
#+end_src

** Claude: Installering og autentisering
Som default bruker ~gptel~ bare ChatGPT-modellene. Legger inn Anthropic sine Claude-modeller også, og setter ~claude-3-haiku~ til å være default modell i stedet for ChatGPT sin modell.

API-nøkkelen til Claude har jeg lagret i en ~~/.authinfo~-fil, som oppdages automatisk av ~auth-source-pick-first-password~-funksjonen:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(gptel-make-anthropic "Claude"
  :stream t
  :key (auth-source-pick-first-password :host "api.anthropic.com"))
#+end_src

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq gptel-backend (gptel-make-anthropic "Claude"
                 :stream t
                 :key (auth-source-pick-first-password :host "api.anthropic.com")))
#+end_src

Setter ~haiku~-modellen til å være standardvalget, da den koster ca. 0 kroner i bruk. 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq gptel-model 'claude-3-haiku-20240307)
#+end_src

** Misc 

Setter org-mode som standardsyntax over Markdown som er default:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq gptel-default-mode #'org-mode)
#+end_src


* ibuffer

Doom Emacs-rammeverket bruker [[https://www.nerdfonts.com/][Nerd Fonts]] for å trylle fram symboler til alt mulig. Bortsett fra ~ibuffer~, som er veldig grå og trist. 

[[https://github.com/seagle0128/nerd-icons-ibuffer][nerd-icons-ibuffer]] legger til ikoner på alle filnavn i ~ibuffer~, basert på den samme Nerd Font-en man allerede har installert. Den tar seg også av fargelegging av kolonner, og legger til såkalt human-readable filstørrelser i stedet for å oppgi alt i bits.  

Installerer pakken: 

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/packages.el
(package! nerd-icons-ibuffer) 
#+end_src

Setter opp en hook som aktiverer ~nerd-icons-ibuffer-mode~ når ~ibuffer~ åpnes. Med mindre jeg er på Emacs på Android eller WSL, hvor jeg ikke har fått det til å virke.

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(use-package! nerd-icons-ibuffer
  :unless (eq system-type 'android)
  :unless (and (eq system-type 'gnu/linux) (getenv "WSLENV"))
  :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

Flisespikker på smådetaljer:

#+begin_src emacs-lisp :tangle ~/repos/dotfiler/doom/config.el
(setq nerd-icons-ibuffer-icon-size 1.2)
#+end_src

